### ISSUE TITLE
what is bg3 on line  61 of the openpose_main.py ？

### ISSUE THREAD

**Issue by evalinlin-00** [RenzoTsai/Human-Pose-Estimation#1]
What is bg3 on line  61 of the openpose_main.py？Isn't there only fall-**-cam0-rgb data in the img folder? When I run the openpose_main.py it just produce an empty folder called output. Hope to get the answer ,thanks.

**Comment by RenzoTsai** [comment]
Sorry for missing this message and omitting some information in the README file. "bg3" should be a folder where you can select images from this dataset and place them inside. This folder is specifically used for obtaining the average background of the target scene (say we have several different scenes, and you can put some images of these scenes into "bg1", "bg2", "bg3"), as indicated in Line 299 of openpose_main.py.

**Comment by RenzoTsai** [comment]
I have updated the README file and related parts in the code. Hope this will be helpful :)
